### ISSUE TITLE
Add asynchronous checkpointing of collected statistics

### ISSUE THREAD

**Issue by fruffy** [dcgym/iroko#16]
Checkpointing the collected bandwidth, queue, and reward stats every 1000 iterations causes a significant slowdown and affects the behavior of the agent. Checkpointing should be asynchronous from the agent's actions

**Comment by gamerDecathlete** [comment]
So like running a separate thread we push results to? As a...extension to this, the stat collecting code really should really be done external to the environment instead of being run inside it (which was more a hack to get result quickly)

**Comment by fruffy** [comment]
The stats collection already runs in asynchronous processes. I currently use the [multiprocessing.Manager](https://docs.python.org/2/library/multiprocessing.html#sharing-state-between-processes) to exchange data between the processes. Not super happy about that but it does the job well enough.  There is the option to use [Arrow ](https://arrow.apache.org/) to share data between different frameworks and write the stats collection in a more efficient language.
I have also been thinking about completely decoupling the queue and bandwidth queries, because bandwidth collection bottlenecks the queue collection quite a lot. Right now iterations are very fast but the stats updates lag behind. That should be an easy fix for queue measurements but not for bandwidth.
