### ISSUE TITLE
Is run_openai_baselines.py be able  to run?

### ISSUE THREAD

**Issue by wushilan** [dcgym/iroko#29]
Hi:
   Thanks for your excellent work. I try to run run_openai_baselines.py in baselines branch. But I met some errors. I want to know if run_openai_baselines has completed and works correctly, or is it a problem in my own operation.
   Best wishes!
   Wu

**Comment by fruffy** [comment]
Yes, we never ended up merging this branch because we did not finish integrating it. Ray worked well enough. I might complete it eventually but right now I would not recommend using it. In theory it should not be too difficult to get this gym to work with baselines.

**Comment by wushilan** [comment]
Thanks for your reply!
Best wishes!
