### ISSUE TITLE
tcp trace not found

### ISSUE THREAD

**Issue by wushilan** [dcgym/iroko#32]
Hi:
   Iroko works well but when I try to plot RTT by

   If transport == "tcp":
            analyze_pcap(rl_algos, tcp_algos, plt_name, runs, data_dir)
   plot_barchart(algos, plt_stats, plt_name)

    in plot.py.
    But it seems no tcp trace and shows 
    result_folder /home/kong/iroko/results/kong-VirtualBox_4/tcp_run0/ppo
    sh: 1: tcptrace: not found.
    How can I solve this problem?
    Best wishes.
    Wu

**Comment by fruffy** [comment]
I think you may have to install tcptrace with `sudo apt install tcptrace`
